#!/bin/csh -f
#TEST-PROGRAM pmemd.cuda
#TEST-DESCRIP signle ion non-softcore TI
#TEST-PURPOSE regression, basic
#TEST-STATE   undocumented

#$1 = PREC_MODEL
#$2 = NETCDF
echo `pwd`

if ( "$1" == "CPU" ) then
   set sander = "mpiexec -np 20 ${AMBERHOME}/bin/pmemd.MPI"
else
   set sander = ${AMBERHOME}/bin/pmemd.cuda_$1
endif


cat > mdin <<EOF
pmemd TI NVT production
&cntrl
! IO =======================================
      irest = 0       ! 0 = start, 1 = restart   THIS OPTION MUST BE PRESENT
        ntx = 1       ! 1 = start, 5 = restart   THIS OPTION MUST BE PRESENT
       ntxo = 1       ! read/write rst as formatted file    
     ioutfm = 0       ! write mdcrd as netcdf
       ntpr = 100   ! mdout print freq         THIS OPTION MUST BE PRESENT
       ntwx = 100   ! mdcrd print freq         THIS OPTION MUST BE PRESENT
       ntwr = 100   ! rst print freq           THIS OPTION MUST BE PRESENT
! DYNAMICS =================================
     nstlim = 2000 ! number of time steps per remd exchange
       imin = 0       ! 0=dynamics, 1=internal minimizer THIS OPTION MUST BE PRESENT
      ntmin = 2       ! mini algorithm. 2=steepest       THIS OPTION MUST BE PRESENT
         dt = 0.003   ! ps/step
! TEMPERATURE ==============================
      temp0 = 298.0   ! target temp
        ntt = 0       ! thermostat (3=Langevin)
! PRESSURE  ================================
        ntp = 0       ! 0=isotropic scaling
! SHAKE ====================================
        ntc = 2
tol=1e-7,
vlimit=20,       ! 1=no shake, 2=HX constrained, 3=all constrained
        ntf = 1       ! 1=cpt all bond E, 2=ignore HX bond E, 3=ignore all bond E
! MISC =====================================
         ig = 98973
        ntb = 1       ! 1=periodic box
      iwrap = 0       ! wrap crds to unit cell
        cut = 10.0
       icfe = 1
       ifsc = 1
       nscm=-1,
    clambda = $LAMBDA,
crgmask = ''
    timask1 = ':1'
    timask2 = ':2'

scmask1 = ":1@H9,H10,H1,H2"
scmask2 = ":2@H1,H2",
tishake=0,

ifmbar_net=1,
gti_scale_beta=1,
scalpha=0.5,
scbeta=1,
gti_cut_sc=2,
gti_cut_sc_on=8,
gti_cut_sc_off=10,
gti_vdw_exp=2,
gti_ele_exp=2,
gti_lam_sch=1,
gti_ele_sc=1,
gti_vdw_sc=1,
gti_output=0,
gti_add_sc=5,

/

&ewald
   chngmask = 1 ! default 1; set to 0 when using piscti softcore
/

EOF

set output = md_SHAKE.$LAMBDA.o

set output_save = $output.$1

touch dummy
$sander -O -i mdin -c inpcrd -p prmtop -o $output -x mdcrd.$LAMBDA <dummy || goto error

#Use different dacdif tolerances based on precision model.
if ( "$1" == "DPFP" ) then
  #7 sig figs
  ../../../../dacdif -r 1.0e-7 $output_save $output
else
  #5 sig figs
  ../../../../dacdif -r 1.0e-5 $output_save $output
endif

/bin/rm -f mdin restrt mdinfo dummy
exit(0)

error:
echo "  ${0}:  Program error"
exit(1)

