#!/bin/csh -f
echo " "
echo "py_resp demo: py_resp on water"
echo " "

$AMBERHOME/bin/py_resp.py -O \
		-i ../../../../examples/PyRESP/test/water/resp-ind/wat.in \
		-o wat.out \
		-t wat.chg \
		-ip ../../../../examples/PyRESP/polarizability/pGM-pol-2016-09-01 \
		-s wat_calc.esp \
		-e ../../../../examples/PyRESP/test/water/esp_wat.dat			|| goto error

foreach i (*out *chg *esp)
../../../dacdif -r 1e-6 $i.save $i
end
exit(0)

error:
echo "  ${0}:  Program error"
exit(1)
