#!/bin/csh -f
#TEST-PROGRAM pmemd.cuda
#TEST-DESCRIP signle ion non-softcore TI
#TEST-PURPOSE regression, basic
#TEST-STATE   undocumented

#$1 = PREC_MODEL
#$2 = NETCDF
echo `pwd`


if ( "$1" == "CPU" ) then
   set sander = "mpiexec -np 20 ${AMBERHOME}/bin/pmemd.MPI"
else
   set sander = ${AMBERHOME}/bin/pmemd.cuda_$1
endif

set output = md_$DIR.o

set output_save = $output.$1

touch dummy
$sander -O -AllowSmallBox -i mdin.$DIR -c inpcrd -p prmtop -o $output <dummy || goto error

#Use different dacdif tolerances based on precision model.
if ( "$1" == "DPFP" ) then
  #7 sig figs
  ../../../../dacdif -f -r 1.0e-7 $output_save $output
else
  #5 sig figs
  ../../../../dacdif -f -r 1.0e-5 $output_save $output
endif

/bin/rm -f restrt mdinfo dummy
exit(0)

error:
echo "  ${0}:  Program error"
exit(1)

