#!/bin/sh

 for x in `cat list`
 do
    for y in `cat case`
    do
       echo $x.$y
       cd $x/$y
       z=`ls | grep 'Run'`
       ./$z
       cd ..
       cd ..
    done
 done

 for x in 'dbf_4'
 do
    for y in "420D" "1F81"
    do
       echo $x.$y
       cd $x/$y
       z=`ls | grep 'Run'`
       ./$z
       cd ..
       cd ..
    done
 done
   
