#!/bin/csh -f
#TEST-PROGRAM pmemd.cuda
#TEST-DESCRIP TO_BE_DEtermined
#TEST-PURPOSE regression, basic
#TEST-STATE   undocumented

#$1 = PREC_MODEL
#$2 = NETCDF

if( ! $?DO_PARALLEL ) then
  setenv DO_PARALLEL " "
  if( $?TESTsander ) then
      set sander = $TESTsander
  else
      set sander = ${AMBERHOME}/bin/pmemd.cuda_$1
  endif
else
  if( $?TESTsander ) then
      set sander = $TESTsander
  else
      set sander = ${AMBERHOME}/bin/pmemd.cuda_$1.MPI
  endif
endif

cat > mdin <<EOF
TRPCage MD
 &cntrl
  imin=0, irest=1, ntx=5,
  nstlim=20, dt=0.002,
  ntc=2, ntf=2,
  ntt=1, tautp=0.5,
  tempi=325.0, temp0=325.0,
  ntpr=1, ntwx=0,ntwr=100000,
  ntb=0, igb=1,
  cut=9999.,rgbmax=9999., ig=71277,
 /
EOF

set output = trpcage_md.out

set output_save = $output.GPU_$1

touch dummy
$DO_PARALLEL $sander -O -o $output -r restrt -x mdcrd < dummy || goto error

#Use different dacdif tolerances based on precision model.
if ( "$1" == "DPFP" ) then
  #7 sig figs
  ../../dacdif -r 1.0e-7 $output_save $output
else
  #4 sig figs
  ../../dacdif -r 1.1e-4 $output_save $output
endif

/bin/rm -f mdin logfile mdinfo dummy restrt mdcrd
exit(0)

error:
echo "  ${0}:  Program error"
exit(1)











